version: "3.7"
services:
  data_importer:
    image: tallguyjenks/watchr:latest
    container_name: watchr
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - /mnt/sql:/mnt/sql
      - /mnt/homelab:/mnt/homelab

networks:
  proxy:
    external: true
