version: "3.7"
services:
  watchr:
    image: tallguyjenks/watchr:latest
    container_name: watchr
    restart: unless-stopped
    networks:
      proxy:
        ipv4_address: 1.1.1.1
    volumes: ["/mnt/homelab:/mnt/homelab"]

networks:
  proxy:
    external: true
