version: "3.7"
services:
  data_importer:
    image: tallguyjenks/strong_app_import:latest
    container_name: strong_app_import
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - /mnt/sql:/mnt/sql
      - /mnt/homelab:/mnt/homelab

networks:
  proxy:
    external: true